/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Validatedll */

#ifndef _Included_Validatedll
#define _Included_Validatedll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Validatedll
 * Method:    suma
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Validatedll_suma
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Validatedll
 * Method:    resta
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Validatedll_resta
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Validatedll
 * Method:    multiplicacion
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Validatedll_multiplicacion
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Validatedll
 * Method:    division
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_Validatedll_division
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Validatedll
 * Method:    validate_L
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Validatedll_validate_1L
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
